CREATE TABLE T1_2015
(
    num_departement int,
    nom_departement varchar[35],
    code_canton int,
    nom_canton varchar[50],
    nb_inscrits int,
    nb_abstentions int,
    abs_pourcent_ins float,
    nb_votants int,
    vot_pourcent_ins float,
    nb_blancs int,
    blancs_pourcent_ins float,
    blancs_pourcent_vot float,
    nb_nuls int,
    nuls_pourcent_ins float,
    nuls_pourcent_vot float,
    nb_exprimés int,
    exp_pourcent_ins float,
    exp_pourcent_vot float,
    num_panneau_liste_1 int,
    nuance_liste_1 varchar[20],
    binome_liste_1 varchar[150],
    nb_sieges_liste_1 int,
    nb_voix_liste_1 int,
    voix_pourcent_ins_liste_1 float,
    voix_pourcent_exp_liste_1 float,
    num_panneau_liste_2 int,
    nuance_liste_2 varchar[20],
    binome_liste_2 varchar[150],
    nb_sieges_liste_2 int,
    nb_voix_liste_2 int,
    voix_pourcent_ins_liste_2 float,
    voix_pourcent_exp_liste_2 float,
    num_panneau_liste_3 int,
    nuance_liste_3 varchar[20],
    binome_liste_3 varchar[150],
    nb_sieges_liste_3 int,
    nb_voix_liste_3 int,
    voix_pourcent_ins_liste_3 float,
    voix_pourcent_exp_liste_3 float,
    num_panneau_liste_4 int,
    nuance_liste_4 varchar[20],
    binome_liste_4 varchar[150],
    nb_sieges_liste_4 int,
    nb_voix_liste_4 int,
    voix_pourcent_ins_liste_4 float,
    voix_pourcent_exp_liste_4 float,
    num_panneau_liste_5 int,
    nuance_liste_5 varchar[20],
    binome_liste_5 varchar[150],
    nb_sieges_liste_5 int,
    nb_voix_liste_5 int,
    voix_pourcent_ins_liste_5 float,
    voix_pourcent_exp_liste_5 float,
    num_panneau_liste_6 int,
    nuance_liste_6 varchar[20],
    binome_liste_6 varchar[150],
    nb_sieges_liste_6 int,
    nb_voix_liste_6 int,
    voix_pourcent_ins_liste_6 float,
    voix_pourcent_exp_liste_6 float,
    num_panneau_liste_7 int,
    nuance_liste_7 varchar[20],
    binome_liste_7 varchar[150],
    nb_sieges_liste_7 int,
    nb_voix_liste_7 int,
    voix_pourcent_ins_liste_7 float,
    voix_pourcent_exp_liste_7 float,
    num_panneau_liste_8 int,
    nuance_liste_8 varchar[20],
    binome_liste_8 varchar[150],
    nb_sieges_liste_8 int,
    nb_voix_liste_8 int,
    voix_pourcent_ins_liste_8 float,
    voix_pourcent_exp_liste_8 float,
    num_panneau_liste_9 int,
    nuance_liste_9 varchar[20],
    binome_liste_9 varchar[150],
    nb_sieges_liste_9 int,
    nb_voix_liste_9 int,
    voix_pourcent_ins_liste_9 float,
    voix_pourcent_exp_liste_9 float,
    num_panneau_liste_10 int,
    nuance_liste_10 varchar[20],
    binome_liste_10 varchar[150],
    nb_sieges_liste_10 int,
    nb_voix_liste_10 int,
    voix_pourcent_ins_liste_10 float,
    voix_pourcent_exp_liste_10 float,
    num_panneau_liste_11 int,
    nuance_liste_11 varchar[20],
    binome_liste_11 varchar[150],
    nb_sieges_liste_11 int,
    nb_voix_liste_11 int,
    voix_pourcent_ins_liste_11 float,
    voix_pourcent_exp_liste_11 float,
    num_panneau_liste_12 int,
    nuance_liste_12 varchar[20],
    binome_liste_12 varchar[150],
    nb_sieges_liste_12 int,
    nb_voix_liste_12 int,
    voix_pourcent_ins_liste_12 float,
    voix_pourcent_exp_liste_12 float,
    PRIMARY KEY (num_departement, code_canton)
);

CREATE TABLE T2_2015
(
    num_departement int, 
    nom_departement varchar[35],
    code_canton int,
    nom_canton varchar[50],
    nb_inscrits int,
    nb_abstentions int,
    abs_pourcent_ins float,
    nb_votants int,
    vot_pourcent_ins float,
    nb_blancs int,
    blancs_pourcent_ins float,
    blancs_pourcent_vot float,
    nb_nuls int,
    nuls_pourcent_ins float,
    nuls_pourcent_vot float,
    nb_exprimés int,
    exp_pourcent_ins float,
    exp_pourcent_vot float,
    num_panneau_liste_1 int,
    nuance_liste_1 varchar[20],
    binome_liste_1 varchar[150],
    nb_sieges_liste_1 int,
    nb_voix_liste_1 int,
    voix_pourcent_ins_liste_1 float,
    voix_pourcent_exp_liste_1 float,
    num_panneau_liste_2 int,
    nuance_liste_2 varchar[20],
    binome_liste_2 varchar[150],
    nb_sieges_liste_2 int,
    nb_voix_liste_2 int,
    voix_pourcent_ins_liste_2 float,
    voix_pourcent_exp_liste_2 float,
    num_panneau_liste_3 int,
    nuance_liste_3 varchar[20],
    binome_liste_3 varchar[150],
    nb_sieges_liste_3 int,
    nb_voix_liste_3 int,
    voix_pourcent_ins_liste_3 float,
    voix_pourcent_exp_liste_3 float,
    PRIMARY KEY (num_departement, code_canton)
);

CREATE TABLE inter_T1_2015(LIKE T1_2015);

COPY inter_T1_2015 *
FROM 'Departementales_cantons_2015_tour_1.csv'
WITH (FORMAT CSV, HEADER, DELIMITER ';');

CREATE TABLE inter_T2_2015 (LIKE T2_2015);

COPY inter_T2_2015 *
FROM 'Departementales_cantons 2015_tour_2.csv'
WITH (FORMAT CSV, HEADER, DELIMITER ';');

INSERT INTO T1_2015
SELECT *
FROM 'Departementales_cantons_2015_tour_1.csv';

INSERT INTO T2_2015
SELECT *
FROM inter_T2_2015;
