PRAGMA foreign_keys = ON;

CREATE TABLE 2015_T1
(
    num_departement int,
    nom_departement char[35] PRIMARY KEY,
    code_canton int,
    nom_canton char[50],
    nb_inscrits int,
    nb_abstentions int,
    %_abs_ins float,
    nb_votants int,
    %_vot_ins float,
    nb_blancs int,
    %_blancs_ins float,
    %_blancs_vot float,
    nb_nuls int,
    %_nuls_ins float,
    %_nuls_vot float,
    nb_exprimés int,
    %_exp_ins float,
    %exp_vot float,
    num_panneau_liste_1 int,
    nuance_liste_1 char[20],
    binome_liste_1 char[150],
    nb_sieges_liste_1 int,
    nb_voix_liste_1 int,
    %_voix_ins_liste_1 float,
    %_voix_exp_liste_1 float,
    num_panneau_liste_2 int,
    nuance_liste_2 char[20],
    binome_liste_2 char[150],
    nb_sieges_liste_2 int,
    nb_voix_liste_2 int,
    %_voix_ins_liste_2 float,
    %_voix_exp_liste_2 float,
    num_panneau_liste_3 int,
    nuance_liste_3 char[20],
    binome_liste_3 char[150],
    nb_sieges_liste_3 int,
    nb_voix_liste_3 int,
    %_voix_ins_liste_3 float,
    %_voix_exp_liste_3 float,
    num_panneau_liste_4 int,
    nuance_liste_4 char[20],
    binome_liste_4 char[150],
    nb_sieges_liste_4 int,
    nb_voix_liste_4 int,
    %_voix_ins_liste_4 float,
    %_voix_exp_liste_4 float,
    num_panneau_liste_5 int,
    nuance_liste_5 char[20],
    binome_liste_5 char[150],
    nb_sieges_liste_5 int,
    nb_voix_liste_5 int,
    %_voix_ins_liste_5 float,
    %_voix_exp_liste_5 float,
    num_panneau_liste_6 int,
    nuance_liste_6 char[20],
    binome_liste_6 char[150],
    nb_sieges_liste_6 int,
    nb_voix_liste_6 int,
    %_voix_ins_liste_6 float,
    %_voix_exp_liste_6 float,
    num_panneau_liste_7 int,
    nuance_liste_7 char[20],
    binome_liste_7 char[150],
    nb_sieges_liste_7 int,
    nb_voix_liste_7 int,
    %_voix_ins_liste_7 float,
    %_voix_exp_liste_7 float,
    num_panneau_liste_8 int,
    nuance_liste_8 char[20],
    binome_liste_8 char[150],
    nb_sieges_liste_8 int,
    nb_voix_liste_8 int,
    %_voix_ins_liste_8 float,
    %_voix_exp_liste_8 float,
    num_panneau_liste_9 int,
    nuance_liste_9 char[20],
    binome_liste_9 char[150],
    nb_sieges_liste_9 int,
    nb_voix_liste_9 int,
    %_voix_ins_liste_9 float,
    %_voix_exp_liste_9 float,
    num_panneau_liste_10 int,
    nuance_liste_10 char[20],
    binome_liste_10 char[150],
    nb_sieges_liste_10 int,
    nb_voix_liste_10 int,
    %_voix_ins_liste_10 float,
    %_voix_exp_liste_10 float
);

CREATE TABLE 2015_T2
(
    num_departement int, 
    nom_departement char[35] PRIMARY KEY,
    code_canton int,
    nom_canton char[50],
    nb_inscrits int,
    nb_abstentions int,
    %_abs_ins float,
    nb_votants int,
    %_vot_ins float,
    nb_blancs int,
    %_blancs_ins float,
    %_blancs_vot float,
    nb_nuls int,
    %_nuls_ins float,
    %_nuls_vot float,
    nb_exprimés int,
    %_exp_ins float,
    %exp_vot float,
    num_panneau_liste_1 int,
    nuance_liste_1 char[20],
    binome_liste_1 char[150],
    nb_sieges_liste_1 int,
    nb_voix_liste_1 int,
    %_voix_ins_liste_1 float,
    %_voix_exp_liste_1 float,
    num_panneau_liste_2 int,
    nuance_liste_2 char[20],
    binome_liste_2 char[150],
    nb_sieges_liste_2 int,
    nb_voix_liste_2 int,
    %_voix_ins_liste_2 float,
    %_voix_exp_liste_2 float,
    num_panneau_liste_3 int,
    nuance_liste_3 char[20],
    binome_liste_3 char[150],
    nb_sieges_liste_3 int,
    nb_voix_liste_3 int,
    %_voix_ins_liste_3 float,
    %_voix_exp_liste_3 float

);

COPY 2015_T1
FROM 'Departementales_cantons_2015_tour_1.csv'
WITH (FORMAT CSV, HEADER, DELIMITER ';', QUOTE '''');

COPY 2015_T2
FROM 'Departementales_cantons 2015_tour_2.csv'
WITH (FORMAT CSV, HEADER, DELIMITER ';', QUOTE '''');